### ISSUE TITLE
Implement Repeater Locking

### ISSUE THREAD

**Issue by JonathanLydall** [JonathanLydall/JavaScript-Redstone-Simulator#1]
Javascript Redstone Simulator - Feedback (2013-02-13 22:12:37)

Do you have any plans for adding repeater locking? I use this
technique quite a bit in my designs.

From the MinecraftWiki.net
"A redstone repeater can be "locked" by powering it from the side with
another redstone repeater. A locked repeater will not change its
output state until unlocked, even if its input changes."

**Comment by AndersBillLinden** [comment]
Is this issue closeable?

**Comment by JonathanLydall** [comment]
Resolved by https://github.com/JonathanLydall/JavaScript-Redstone-Simulator/pull/20.
